# Model Configuration

# MIL Model Settings
mil_model:
  feature_extractor: "resnet18"
  pretrained: true
  feature_dim: 512
  hidden_dim: 256
  num_classes: 2
  dropout: 0.5
  attention:
    hidden_dim: 128
    num_heads: 1

# GNN Model Settings
gnn_model:
  in_channels: 512
  hidden_channels: 256
  num_layers: 3
  dropout: 0.5
  edge_dim: 32
  aggregation: "mean"

# Combined Model Settings
combined_model:
  fusion_type: "concat"
  fusion_hidden_dim: 256
  use_attention: true
  freeze_feature_extractor: false

# Model Training
training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.0001
  lr_scheduler:
    type: "reduce_on_plateau"
    patience: 5
    factor: 0.5
    min_lr: 0.00001
  early_stopping:
    patience: 10
    min_delta: 0.001

# Model Evaluation
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
    - roc_auc
  confidence_threshold: 0.5
  num_visualization_samples: 10