# Training Configuration

# Data Settings
data:
  train_path: "data/train"
  val_path: "data/val"
  test_path: "data/test"
  patch_size: 50
  num_patches: 100
  overlap: 0.5
  
  # Data Augmentation
  augmentation:
    enabled: true
    horizontal_flip: true
    vertical_flip: true
    rotation: true
    color_jitter:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1
    random_crop:
      enabled: true
      size: 48
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Training Process
training:
  seed: 42
  num_workers: 4
  pin_memory: true
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  
  # Optimization
  optimizer:
    type: "adam"
    learning_rate: 0.0001
    weight_decay: 0.0001
    beta1: 0.9
    beta2: 0.999
    
  # Learning Rate Scheduling
  lr_scheduler:
    type: "reduce_on_plateau"
    mode: "min"
    factor: 0.5
    patience: 5
    min_lr: 0.000001
    
  # Early Stopping
  early_stopping:
    monitor: "val_loss"
    patience: 10
    min_delta: 0.001
    mode: "min"

# Logging and Checkpoints
logging:
  project_name: "histopathology-analysis"
  log_every_n_steps: 50
  
  # MLflow settings
  mlflow:
    tracking_uri: "http://localhost:5000"
    experiment_name: "histopathology-training"
    
  # Checkpointing
  checkpointing:
    dirpath: "checkpoints"
    filename: "model-{epoch:02d}-{val_loss:.2f}"
    monitor: "val_loss"
    mode: "min"
    save_top_k: 3
    save_last: true

# Validation
validation:
  val_check_interval: 1.0
  limit_val_batches: 1.0
  
  # Metrics to track
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - roc_auc
    
  # Visualization
  visualize_predictions: true
  num_samples_to_visualize: 10
  save_visualizations: true